name: build
on:
  release:
    types: [created]
  push:
    paths-ignore:
      - '**.md'
      - '**.txt'
    branches:
      - master
  pull_request:
    branches:
      - master
permissions:
  contents: write
jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
            binary_name: auto-editor-linux-x86_64
          - os: macos-13
            arch: x86_64
            binary_name: auto-editor-macos-x86_64
          - os: macos-latest
            arch: arm64
            binary_name: auto-editor-macos-arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Nim
        uses: iffy/install-nim@v5
        with:
          version: binary:stable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            sudo apt-get update
            sudo apt-get install -y build-essential pkg-config nasm git
          elif [ "${{ matrix.os }}" = "macos-13" ]; then
            brew install nasm
            export MACOSX_DEPLOYMENT_TARGET=13.0
          elif [ "${{ matrix.os }}" = "macos-latest" ]; then
            export MACOSX_DEPLOYMENT_TARGET=14.0
          fi
      - name: Build FFmpeg
        run: nimble makeff
      - name: Compile
        run: nimble make
      - name: Test
        run: nimble test
      - name: Rename binary
        run: |
          mv auto-editor ${{ matrix.binary_name }}
      - name: Upload to Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.binary_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Artifact (for non-release builds)
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v4
        with:
          name: auto-editor-${{ matrix.os }}-${{ matrix.arch }}
          path: ${{ matrix.binary_name }}

  windows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Nim
        uses: iffy/install-nim@v5
        with:
          version: binary:stable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install mingw-w64
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64 mingw-w64-tools mingw-w64-x86-64-dev
          sudo apt-get install -y build-essential pkg-config nasm git
      - name: Build FFmpeg
        run: nimble makeffwin
      - name: Compile
        run: nimble windows
      - name: Rename binary
        run: |
          mv auto-editor.exe auto-editor-windows-amd64.exe
      - name: Upload to Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: auto-editor-windows-amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Artifact (for non-release builds)
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v4
        with:
          name: auto-editor-win-amd64
          path: auto-editor-windows-amd64.exe