name: build
on:
  release:
    types: [created]
  push:
    paths-ignore:
      - '**.md'
      - '**.txt'
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Nim
        uses: iffy/install-nim@v5
        with:
          version: binary:stable
      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config nasm git
      - name: Build FFmpeg
        run: nimble makeffmpeg
      - name: Compile
        run: nimble make
      - name: Test
        run: ./auto-editor info example.mp4

